name: CI/CD

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    env:
      aws-region: "us-east-1"
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Set Up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '16'

    - name: Install Dependencies
      run: npm install

    - name: Build
      run: npm run build

    - name: Clear Bucket
      run: aws s3 rm s3://finny-app-logs --recursive
      env:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: "us-east-1"

    - name: Deploy to S3 Bucket
      uses: jakejarvis/s3-sync-action@v0.3.0
      with:
        args: --acl public-read --follow-symlinks --delete
      env:
        aws-s3-bucket: ${{ secrets.AWS_S3_BUCKET }}
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
